tech_talent_blog_kfk/config/routes.rb
Rails.application.routes.draw do
  
  root 'blog_posts#index'
  
  get 'your_posts' => 'blog_posts#your_posts'
  get 'user_posts' => 'blog_posts#user_posts'
  
  devise_for :users
  resources :users
  resources :comments
  resources :blog_posts

end

tech_talent_blog_kfk/app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
    has_many :comments
    belongs_to :user
end

tech_talent_blog_kfk/app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :blog_post
    belongs_to :user
end

tech_talent_blog_kfk/app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :blog_posts
  has_many :comments
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

tech_talent_blog_kfk/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :name)}
    
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :name, :current_password)}
    
  end
end

tech_talent_blog_kfk/app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]
  
  before_filter :authenticate_user!

  def your_posts
    
  end
  
  def user_posts
    @user = User.find(params[:id])
  end


  # GET /blog_posts
  # GET /blog_posts.json
  def index
    @blog_posts = BlogPost.all
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
    @comment = Comment.new
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully created.' }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1
  # PATCH/PUT /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: 'Blog post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :author, :blog_entry, :user_id)
    end
end

tech_talent_blog_kfk/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to blog_post_path(id: @comment.blog_post_id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author, :comment_entry, :blog_post_id, :user_id)
    end
end

tech_talent_blog_kfk/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

tech_talent_blog_kfk/app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

tech_talent_blog_kfk/app/helpers/comments_helper.rb
module CommentsHelper
end

tech_talent_blog_kfk/app/helpers/users_helper.rb
module UsersHelper
end

tech_talent_blog_kfk/app/views/blog_posts/_form.html.erb
<%= form_for(@blog_post) do |f| %>
  <% if @blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
      <% @blog_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :title, class: "form-control", placeholder: "Post Title" %>
  </div>
  <div class="form-group">
    <%= f.text_area :blog_entry, class: "form-control", :rows => 7, placeholder: "Speak Your Mind" %>
  </div>
  <div class="form-group cant-see-me">
    <%= f.number_field :user_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

tech_talent_blog_kfk/app/views/blog_posts/edit.html.erb
<h1>Editing Blog Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_post, class: "btn btn-warning" %>
<%= link_to 'Back', blog_posts_path, class: "btn btn-primary pull-right" %>

tech_talent_blog_kfk/app/views/blog_posts/index.html.erb
<h1>Current Blog Posts</h1>

<div class="row">
  <% @blog_posts.each do |blog_post| %>
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= link_to blog_post.title, blog_post %>
    </div>
    <div class="panel-body">
      by <%= link_to blog_post.user.name, user_posts_path(id: blog_post.user.id) %> at <%= blog_post.created_at.strftime('%m/%d/%Y %I:%M:%S %p') %>
      <br />
      <p><%= blog_post.blog_entry[0..250] %>...[<%= link_to "Read More", blog_post %>]</p>
    </div>
    <div class="panel-footer">
      <% if signed_in? %>
      <% if current_user.id ==blog_post.user.id %>
      <!--
      removing the equals sign after the karet percent sign makes what follows hidden
      <% link_to 'Show', blog_post, class: "btn btn-primary" %> 
      -->
      <%= link_to 'Edit', edit_blog_post_path(blog_post), class: "btn btn-teal" %>
      <%= link_to 'Destroy', blog_post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
      <% end %>
      <% end %>
    </div>
  </div>
<% end %>

tech_talent_blog_kfk/app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_posts_path, class: "btn btn-primary pull-right" %>

tech_talent_blog_kfk/app/views/blog_posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-primary">
  <div class="panel-heading">
    <%= @blog_post.title %>
  </div>
  <div class="panel-body">
    <p>by <%= @blog_post.user.email %></p>
    <p><%= @blog_post.blog_entry %></p>
</div>

<div class="panel panel-success">
  <div class="panel-heading">
    Make A Comment
  </div>
  <div class="panel-body">
    <%= render 'comments/form' %>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-header">
    <h4>Comments</h4>
  </div>
  <% @blog_post.comments.each do |comment| %>
  <div class="panel-body">
    <p><strong><%= comment.user.name %></strong> said: </p>
    <p> <%= comment.comment_entry %> </p>
  </div>
  <% end %>
</div>

<div>
  <%= link_to 'Edit Post', edit_blog_post_path(@blog_post), class: "btn btn-teal" %>
  <%= link_to 'Back', blog_posts_path, class: "btn btn-primary pull-right" %>
</div>

tech_talent_blog_kfk/app/views/blog_posts/user_posts.html.erb
<h1><%= @user.name %>'s Blog Posts</h1>

  <% @user.blog_posts.each do |blog_post| %>
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= link_to blog_post.title, blog_post %>
    </div>
    <div class="panel-body">
      by <%= blog_post.user.name %> at <%= blog_post.created_at.strftime('%m/%d/%Y %I:%M:%S %p') %>
      <br />
      <p><%= blog_post.blog_entry[0..250] %>...[<%= link_to "Read More", blog_post %>]</p>
    </div>
    <div class="panel-footer">
        <% if current_user.id == @user.id %>
      <!--removing the equals sign after the karet percent sign makes what follows hidden-->
      <% link_to 'Show', blog_post, class: "btn btn-primary" %>
      <%= link_to 'Edit', edit_blog_post_path(blog_post), class: "btn btn-teal" %>
      <%= link_to 'Destroy', blog_post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
      <% end %>
    </div>
  </div>

<% end %>
</div>

<br>

<%= link_to 'New Blog post', new_blog_post_path, class: "btn btn-success" %>

tech_talent_blog_kfk/app/views/blog_posts/your_posts.html.erb
  <% current_user.blog_posts.each do |blog_post| %>
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= link_to blog_post.title, blog_post %>
    </div>
    <div class="panel-body">
      by <%= blog_post.user.name %> at <%= blog_post.created_at.strftime('%m/%d/%Y %I:%M:%S %p') %>
      <br />
      <p><%= blog_post.blog_entry[0..250] %>...[<%= link_to "Read More", blog_post %>]</p>
    </div>
    <div class="panel-footer">
      <!--removing the equals sign after the karet percent sign makes what follows hidden-->
      <% link_to 'Show', blog_post, class: "btn btn-primary" %>
      <%= link_to 'Edit', edit_blog_post_path(blog_post), class: "btn btn-teal" %>
      <%= link_to 'Destroy', blog_post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
    </div>
  </div>
</div>
<% end %>